# -*- coding: utf-8 -*-
"""Variables and Data Types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z42gJDBMJHpd1ZWcfqo7W0PU70kgWZdm

# **1. Variables**

In Python, variables are used to store data. There’s no need to specify the type of data when creating a variable because Python automatically determines it.
"""

# Defining variables in Python
x = 5  # A variable storing an integer
y = 3.14  # A variable storing a floating-point number
name = "Alaa"  # A variable storing a string

# Printing the values of the variables
print("Value of x:", x)
print("Value of y:", y)
print("Value of name:", name)

"""Explanation:

x = 5: The variable x is assigned the value 5, which is an integer.

y = 3.14: The variable y is assigned the value 3.14, which is a float (decimal number).

name = "Alaa": The variable name is assigned the string value "Alaa".

We use print() to output the values of the variables.

# **2. Basic Data Types**

Python supports several basic data types. Some of the main ones are:

1. int: Integer numbers.


2. float: Floating-point numbers (decimal).


3. str: Strings (text).


4. bool: Boolean values (True or False).


5. list: Lists.


6. tuple: Tuples.


7. dict: Dictionaries.
"""

# Examples of basic data types
integer_var = 10  # Integer
float_var = 3.14  # Float
string_var = "Hello, World!"  # String
boolean_var = True  # Boolean value

# Compound data types
list_var = [1, 2, 3, 4, 5]  # List containing integers
tuple_var = (10, 20, 30)  # Tuple containing integers
dict_var = {"name": "Alaa", "age": 25}  # Dictionary with keys and values

# Printing the values
print("Integer:", integer_var)
print("Float:", float_var)
print("String:", string_var)
print("Boolean:", boolean_var)
print("List:", list_var)
print("Tuple:", tuple_var)
print("Dictionary:", dict_var)

"""Explanation:

integer_var = 10: A variable holding an integer (int).

float_var = 3.14: A variable holding a floating-point number (float).

string_var = "Hello, World!": A variable holding a string (str).

boolean_var = True: A variable holding a boolean value (bool).

list_var = [1, 2, 3, 4, 5]: A variable holding a list of integers (list).

tuple_var = (10, 20, 30): A variable holding a tuple of integers (tuple).

dict_var = {"name": "Alaa", "age": 25}: A variable holding a dictionary with keys and values (dict).

# **3. Type Casting**

Python provides ways to convert data from one type to another using built-in functions like int(), float(), str().
"""

# Type casting between data types
int_var = int(3.14)  # Converting from float to int
float_var = float(10)  # Converting from int to float
str_var = str(25)  # Converting from int to string

# Printing the results after conversion
print("Converted int:", int_var)
print("Converted float:", float_var)
print("Converted string:", str_var)

"""Explanation:

int(3.14): Converts the floating-point number 3.14 to an integer, which results in 3.

float(10): Converts the integer 10 to a float, which results in 10.0.

str(25): Converts the integer 25 to a string, resulting in "25".

# **4. Checking Data Types**

You can check the type of any variable using the built-in type() function.
"""

# Checking the type of variables
print("Type of integer_var:", type(integer_var))
print("Type of float_var:", type(float_var))
print("Type of string_var:", type(string_var))
print("Type of boolean_var:", type(boolean_var))

"""Explanation:

type(variable): Returns the type of the given variable.

For example, type(integer_var) will return <class 'int'>, indicating that the variable is of type integer.

# **Summary of Data Types in Python:**

int: Integer type (whole numbers).

float: Floating-point type (decimal numbers).

str: String type (text).

bool: Boolean type (True or False).

list: Ordered collection of items.

tuple: Immutable ordered collection.

dict: Key-value pairs (hash map).
"""